linters-settings:
  custom:
    cyclop:
      path: cyclop.so
      description: calculates cyclomatic complexity
    autoimports:
      path: autoimports.so
      description: autoimports

linters:
  disable-all: true
  enable:
    - typecheck
    - cyclop
    - autoimports